# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bf3cdfd33318946014f380d38d1071df01288ec2d2abc2c4276d5847ba2ffc72126ac0d8499879fe73d67bdd7075f49210b51774bafb0f819325db4585ca93c

test:
  secret_key_base: c07869453f0e8c25619ec98ca7cc2d56768c6f03e7178273886a00a4d1fdc277c6ca9f671de326275f4acac023926954a4cf4f110ca1e4195a89dffe7ce9c95e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
